### ISSUE TITLE
Allow user-provided environment configuration for packages

### ISSUE THREAD

**Issue by colincasey** [heroku/buildpacks-deb-packages#87]
Many packages require some extra environment configuration in order to work properly after installation. Several of these we are aware of (e.g.; `git`, `proj-data`, `tesseract-ocr`, etc.) but we can't easily identify these packages ahead of time so there are many that we aren't aware of. 

In order to accommodate packages that do require environment configuration, I think we need two options:

1. For known packages, this buildpack should add the required package configuration automatically for the user.
2. For unknown packages, this buildpack's configuration should allow the user to specify the required package configuration manually.
3. 
Ideally, the user should never have to resort to option 2 but that's not realistic. The goal would be to support this manual configuration use case, identify when it's being used, and work to eliminate the need for manual configuration.
      
An idea for how the user might specify environment configuration for a package is provided in #83:

```toml
[[com.heroku.buildpacks.deb-packages.install]]
name = "git"

  [com.heroku.buildpacks.deb-packages.install.env]
  GIT_EXEC_PATH = "{install_dir}/usr/lib/git-core"
  GIT_TEMPLATE_DIR = "{install_dir}/usr/share/git-core/templates"
```

In my opinion, I think the environment should be separated from the package. E.g.; 

```toml
[[com.heroku.buildpacks.deb-packages.env]]
GIT_EXEC_PATH = "{install_dir}/usr/lib/git-core"
GIT_TEMPLATE_DIR = "{install_dir}/usr/share/git-core/templates"
```

**Comment by colincasey** [comment]
Closing this as manual configuration of environment variables can be provided through existing CNB methods. E.g.; specify custom environment variables in `project.toml`:

```toml
[[io.buildpacks.build.env]]
name='HELLO'
value='WORLD'
```
> https://buildpacks.io/docs/for-app-developers/how-to/build-inputs/use-project-toml/#specify-buildpacks-and-envs

Or, using an [inline-buildpack](https://buildpacks.io/docs/for-app-developers/how-to/build-inputs/use-inline-buildpacks/) to create [custom environment configurations](https://buildpacks.io/docs/for-buildpack-authors/how-to/write-buildpacks/specify-env/).
